README.md
package.json
src/refiners/dayOverlapRefiner.js
src/refiners/impliedAMEndRefiner.js
src/refiners/impliedPMStartRefiner.js
src/test/parser.test.js

update a few references to the old project location

Rebrand to tickbin

---

README.md

Update README to specify they need node 4

---

package.json
src/errors/NoMeridiemError.js
src/parser.js
src/parsers/militaryParser.js
src/refiners/requireMeridiemRefiner.js
src/test/parser.test.js
src/test/requireMeridiemRefiner.test.js

Always require a meridiem so we don't guess (incorrectly) at the times

Require meridiem

---

src/refiners/dayOverlapRefiner.js
src/refiners/impliedAMEndRefiner.js
src/refiners/impliedPMStartRefiner.js
src/test/entry.test.js
src/test/parser.test.js

Fix: refiners that only work on ranges will not error on single dates

---

package.json

update yargs, moment, eslint, lodash

---

src/account.js
src/commands/tick-login.js
src/commands/tick-register.js
src/config.js
src/entry.js
src/test/entry.test.js

This adds the user's ID to every entry they create. On login and registration, it also updates the current set of entries to use the user's ID.
I haven't worked on the client in a while, anyone in @tickbin/core want to give this a review?
Resolves #178 
Resolves #177

Add user ID to entries

---

src/commands/tick-log.js

fix: tell users to use tick commit

---

package.json

Update the following packages:
* axios 0.9.0 to 0.11.0 - mostly bug fixes
* untildify 2.1.0 to 3.0.2 - mostly es2015 code conversion

Deps update

---

src/commands/tick-login.js
src/commands/tick-register.js
src/server.js
src/test/server.test.js

Resolves #185 and resolves #199

Update API endpoint and fix login/registration error output

---

src/commands/tick-sync.js
src/sync.js
src/test/sync.test.js

hacky hotfix to sync everything always... slower and displays errors that need fixing

last_sync doc causes problems, sync everything

---

src/commands/output.js

Commit and Remove "+" and "-" changed to be more visible

---

src/sync.js

we will be adding design docs to the remote databases. This prevents those docs from being synced down to the user's local db.

feat(sync): filter pulled entries

---

src/commands/tick-rm.js

feat: Provide a warning message when no remove ID is provided.

---

README.md

feat: More description on dev config.

---

src/commands/tick-log.js

feat: tick list has --hide-details flag to hide entry details

---

src/commands/tick-register.js

feat: Directs users to tickbin.com when registering.

---

src/commands/output.js
src/commands/tick-log.js

fix: Icon is no longer included as a column in csv.

---

src/commands/tick-log.js

fix: Fixed parse error message and type filter example

---

src/commands/tick-log.js

feat: hide-summary boolean to hide the daily summary in the tick log command

---

package.json
src/commands/output.js
src/test/create.test.js
src/test/query.test.js
src/test/upgrade.test.js
src/upgrade.js

feat(entry): entry supplies message without time

---

src/commands/tick-start.js
src/commands/tick-stop.js
src/tick.js

Wire up stop and start command

---

src/commands/tick-logout.js
src/config.js
src/tick.js

Resolves #85  
Removes user and remote from config file.

feat: Logout command 

---

src/commands/tick-login.js
src/commands/tick-register.js

feat: Login and register error messages

---

src/commands/tick-start.js
src/commands/tick-stop.js

* `tick start` saves the current timer to the timers document
* `tick stop` uses the start time, current time as the the end time, user's input message and commits an entry.
Resolves #254 
Resolves #255

Basic start and stop command logic

---

src/commands/output.js
src/commands/tick-start.js
src/commands/tick-stop.js

* `tick start` parses message for start time or uses current time
* `tick stop` parses message for end time or uses current timer
* `tick stop` can override message provided by `tick start`
* `tick stop` prompts if no message was provided
Resolves #256 
Resolves #257

Advanced timer functionality

---

src/commands/output.js
src/commands/tick-cancel-timer.js
src/tick.js

`tick cancel-timer` will cancel the current timer without committing
Resolves #262

Cancel timer command

---

src/commands/tick-timer.js
src/tick.js

List timer details
Resolves #264

`tick timer` command

---

README.md
src/commands/tick-cancel-timer.js
src/commands/tick-start.js
src/commands/tick-stop.js
src/tick.js

I will be leaving this PR open an adding to it as new features are still being implemented.
Resolves #261

Document new timer commands

---

src/commands/tick-login.js
src/commands/tick-register.js

* Resolves #286 - allow registration without remote
* Resolves #247 - registration prompt message bug

Fix registration bugs

---

src/commands/tick-stop.js
src/test/query.test.js

I ended up refactoring the stop command in order to try and simplify things to solve #279. Tests would be nice for this, there are several cases for user input when stopping a timer. See the large comment block for all the cases I can think of. 
@tickbin/core If I can get a second set of eyes on this, and let me know if things make sense, or if there is a totally different approach I should be taking. I may be stuck in a single minded state on this problem.
Resolves #275 
Resolves #279

Requires message for stopping a timer

---

src/commands/tick-log.js

Resolves #147
Can I get a review on this from @tickbin/core? Just wondering if someone had something else in mind for how to display the information. I'm simply providing it at the end of the log.

Total and tag summary for tick log

---

package.json

pouchdb-find was not functioning as described, which caused the constant revisions on index files.
Resolves #312

chore(package): update pouchdb-find to version 0.10.4

---

README.md

MemoryLeaf has change it's name, this should be reflected in the README

chore: change name to Two Story Robot

---

package.json

fix(tickbin-parser): update dependencies

---

package.json

chore(package): update chrono-node to version 1.3.4

---

npm-shrinkwrap.json
package.json
src/test/create.test.js
src/test/timers.test.js

chore(package): update sinon to version 7.3.2

---

npm-shrinkwrap.json
package.json

fix(package): update yargs to version 13.3.0

---

npm-shrinkwrap.json
package.json

chore(package): update standard-version to version 7.0.0

---

npm-shrinkwrap.json
package.json

chore(package): update eslint to version 6.1.0

---

.semaphore/semaphore.yml
README.md

Update Semaphore 2 configuration
